version: '3.8'
services:
  postgres-pedido:
    image: postgres:15-alpine
    container_name: postgres-pedido
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pedido_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-pedido-data:/var/lib/postgresql/data

  pedido-service:
    build:
      context: ./
    container_name: pedido-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-pedido:5432/pedido_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - postgres-pedido

volumes:
  postgres-pedido-data:
