version: '3.8'
services:

  postgres-pedido:
    image: postgres:15
    container_name: postgres-pedido
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pedido_db
    ports:
      - "5432:5432"

  postgres-estoque:
    image: postgres:15
    container_name: postgres-estoque
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: estoque_db
    ports:
      - "5433:5432"

  postgres-cliente:
    image: postgres:15
    container_name: postgres-cliente
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cliente_db
    ports:
      - "5434:5432"

  pedido-service:
    build:
      context: ./pedido
    container_name: pedido-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-pedido:5432/pedido_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres-pedido

  estoque-service:
    build:
      context: ./estoque
    container_name: estoque-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-estoque:5432/estoque_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres-estoque

  cliente-service:
    build:
      context: ./cliente
    container_name: cliente-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-cliente:5432/cliente_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres-cliente