version: '3.8'
services:
  postgres-cliente:
    image: postgres:15-alpine
    container_name: postgres-cliente
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cliente_db
    ports:
      - "5434:5432"
    volumes:
      - postgres-cliente-data:/var/lib/postgresql/data

  cliente-service:
    build:
      context: ./
    container_name: cliente-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-cliente:5432/cliente_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - postgres-cliente

volumes:
  postgres-cliente-data:
